version: "2"
services:
  client:
    build:
      "client"
      # context: client/
      # dockerfile: Dockerfile-client
    container_name: client
    environment: 
      - SERVER_URL=server:8080
    # ports:
    #   - "2000:3000"
    networks:
      - lognet
    # restart: always
    working_dir: /home/app
    volumes:
      - ./client/app:/home/app
    command: sh -c 'npm i && node client.js'
    depends_on:
      - "server"
  server:
    build:
      "server"
      # context: server/
      # dockerfile: Dockerfile-server
    container_name: server
    # restart: always
    working_dir: /home/app
    volumes:
      - ./server/app:/home/app
    ports:
      - "8080:8080"
    networks:
      - lognet
    command: sh -c 'npm i && node server.js'

networks:
  lognet:
    driver: bridge
